# Generated by Django 4.2.1 on 2023-06-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_jason',
            new_name='items_json',
        ),
    ]
